In [1]:
import numpy as np

In [11]:
a = np.array([1,2,3],dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [5]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
#get dimension
a.ndim
b.ndim

2

In [8]:
#get shape
b.shape

(2, 3)

In [12]:
#get type
a.dtype

dtype('int16')

In [13]:
#get size
a.itemsize #int32 for big data  and size of int32 is  int16*2

2

In [15]:
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
#get specific element  [row,col]
c[0,6]

7

In [17]:
#get specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
#get specific col
c[:,2]

array([ 3, 10])

In [23]:
#get a little more fancy [startindex : endindex : stepsize] stepsize mean jumpstep

c[0,1:5:2]

array([2, 4])

In [26]:
#update specific element
c[1,5]=20
print(c)

c[:,2]=5
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [29]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])#compose as multi-tuple
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
d[0,1,1]
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [33]:
#replace 
d[:,1,:] =[[9,9],[8,8]]
print(d)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [35]:
#all 0s matrix
np.zeros((2,3),dtype='int32')

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
#all 1s matrix
np.ones((4,2,3),dtype='int16')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [37]:
#all other number(shape,value)
np.full((3,2,1),99)

array([[[99],
        [99]],

       [[99],
        [99]],

       [[99],
        [99]]])

In [39]:
#other number (full_like)
np.full_like(d,99)
#same
np.full(d.shape,99)

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [41]:
# random decimal numbers
np.random.rand(4,2)
#if want to shape
np.random.random_sample(d.shape)

array([[[0.83789336, 0.79490386],
        [0.79560037, 0.15677965]],

       [[0.40144789, 0.27949733],
        [0.37875842, 0.80231785]]])

In [47]:
#random int (range,size)
np.random.randint(-7,7,size=(2,3))

array([[ 1,  0,  5],
       [ 0, -3, -6]])

In [44]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [55]:
t1=np.ones((5,5),dtype='int16')
print(t1)
t2=np.zeros((3,3),dtype='int16')
t2[1,1]=9
print(t2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [58]:
t1[1:4,1:4]=t2
print(t1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#be careful when copy

In [68]:
print(a)

[100   2   3]


In [70]:
e=a.copy()
e[0]=99
print(a)
print(e)# equal mean a and e link,.copy() address this problem

[100   2   3]
[99  2  3]


# Mathmatics

In [71]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [72]:
a+1#if a += 1,a will be updated

array([2, 3, 4, 5])

In [73]:
a-1

array([0, 1, 2, 3])

In [74]:
a * 2

array([2, 4, 6, 8])

In [75]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [76]:
a**2

array([ 1,  4,  9, 16])

In [77]:
b=np.array([0,1,0,1])
a+b

array([1, 3, 3, 5])

In [79]:
# sin cos
np.sin(a)

np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

# Liner Algebra

In [81]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

np.matmul(a,b)#矩阵乘法运算

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

# statistics

In [84]:
a=np.array([[1,2,3,4],[4,5,6,7]])

In [85]:
np.min(a)

1

In [86]:
np.max(a,axis=1)#显示出最大值的那一列

array([4, 7])

In [87]:
np.max(a,axis=0)#最大h值所在的那一行

array([4, 5, 6, 7])

In [88]:
np.sum(a)#同理axis=1对列求和

32

# Reorganizing matrix

In [89]:
before=np.array([[1,2,3,4],[4,5,6,7]])
print(before)

after=before.reshape((4,2))
print(after)#before与after的元素个数必须相同

[[1 2 3 4]
 [4 5 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [91]:
#vertical stack
v1=np.array([[1,2,3,4]])
v2=np.array([[5,6,7,8]])
np.vstack((v1,v2,v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [94]:
#horizonal stack
h1=np.ones((4,2))
h2=np.zeros((4,1))
np.hstack((h1,h2))

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])

# Miscellaneous

# load data from flie

In [ ]:
data_file = np.genfromtxt('path',delimiter=miter=',')
data_file = data_file.astype('int32')

# boolean Masking and advanced indexing

In [ ]:
np.all(data_file>50,axis=0)

In [ ]:
data_file>50

In [ ]:
((data_file >50) & (data_file<100))

In [ ]:
((data_file >50) & (data_file<100))

In [97]:
t1=np.array(range(1,31))
t1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [99]:
t2=t1.reshape((6,5))
t2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [102]:
t2[2:4,:2]

array([[11, 12],
       [16, 17]])

In [107]:
t2[(0,1,2,3),(1,2,3,4)]

array([ 2,  8, 14, 20])

In [112]:
t2[[(0,-2:),(-2,-2:),(-1,-2:)]]

SyntaxError: invalid syntax (Temp/ipykernel_13976/116046574.py, line 1)

In [113]:
t2[(0,4,5),-2:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])